modLoader="kotlinforforge"
loaderVersion="${loaderVersionRange}"
license='${modLicense}'

[[mods]]
modId="${modId}"
version="${modVersion}"
displayName="${modName}"
credits="Thanks to thedarkcolour and all the contributors for making Kotlin for Forge"
authors="${modAuthors}"
description='''${modDescription}'''

[[dependencies.${modId}]]
modId="neoforge"
type="required"
versionRange="${neoVersionRange}"
ordering="NONE"
side="BOTH"

[[dependencies.${modId}]]
modId="minecraft"
type="required"
versionRange="${minecraftVersionRange}"
ordering="NONE"
side="BOTH"
